### ISSUE TITLE
Suggested world tweaks

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/wasi-cloud-core#11]
Hi!  I'd like to make two suggested tweaks to the current world:
* Following the emerging convention to name worlds that only contain imports and are meant for inclusion in other worlds "`imports`" (e.g., `wasi:cli/imports`), could the current `cloud-core` world be renamed to `imports`?
  * Later, we could add other worlds to the `wasi:cloud-core` package that included `imports` and defined various exports (e.g., a `wasi:cloud-core/http-service` world could `include imports` and `export wasi:http/incoming-handler`.
* I think the (`cloud-core`|`imports`) world shouldn't be attempting to `include` whole packages (I'd be surprised if this actually compiles today?) but rather particular worlds nested inside packages.  E.g., instead of `include wasi:keyvalue`, I'd expect `include wasi:keyvalue/imports`.
  * We can factor out a `wasi:http/imports` world in the wasi-http proposal that only has the imports, but not the `outgoing-handler` export.

**Comment by Mossaka** [comment]
Thanks for rasing the issue!

Ah, I think this is related to my PR: https://github.com/WebAssembly/wasi-cloud-core/pull/10#discussion_r1457893409

Yes, I agree that we should rename `cloud-core` to `imports` and remove any exports.

**Comment by lukewagner** [comment]
Oh great, you're way ahead of me :)  Feel free to close this issue now or leave it open until you think it's resolved.

**Comment by Mossaka** [comment]
It seems like this has been resolved.
