### ISSUE TITLE
Consider collapsing interfaces into this repo

### ISSUE THREAD

**Issue by lann** [WebAssembly/wasi-cloud-core#2]
There are currently 7 (?) repositories for the [various WASI cloud interface proposals](https://github.com/WebAssembly/WASI/issues/520). I wonder if it would make sense - pragmatically - to collapse them all into this repo. This would simplify synchronization of the cloud core world and reduce admin overhead if/when changes are needed to repo permissions, etc.

**Comment by Mossaka** [comment]
I will add a `deps.toml` to this repo.
